### ISSUE TITLE
请求提供构建辅助信息

### ISSUE THREAD

**Issue by Haocen2004** [Klta-kyo/MaiScan#1]
gradle相关文件怎么都没有包含www
建议是使用.gitignore文件控制而不是把src单独复制出来给git
以及用Android studio直接创建版本控制应该就会给一份适合Android项目的.gitignore 一般用那个就够了

**Comment by Klta-kyo** [comment]
谢谢提醒，已修改gitignore。
之前是使用Android Studio生成的git上传，没有注意具体配置。不熟悉安卓开发见谅。
若有其他问题随时提出，谢谢！
